### ISSUE TITLE
Setup profile style

### ISSUE THREAD

**Issue by oyvindrii** [NoroffFEU/fed2-js2-ca-Oyvindeavor#34]
### Setup Profile Style

**Description:**
Create and implement simple CSS styles for the Profile page

**Tasks:**
- [ ] Design layout for the profile
- [ ] User should be able to view recent posts they have made 
- [ ] User should be able to edit the profile changing the banner, avatar and bio
