### ISSUE TITLE
create updateprofile function

### ISSUE THREAD

**Issue by oyvindrii** [NoroffFEU/fed2-js2-ca-Oyvindeavor#37]
#### **Description**
Use the existing function located in `src/js/api/profile/update.js`@

```
export async function updateProfile(username, { avatar, banner }) {} 
```

it should take in the username as a parameter then change the avatar url,banner, bio text. 

implement it with the `src/js/ui/profile/update.js`  

```
export async function onUpdateProfile(event) {}
```

#### **Tasks**

- [x] Make sure the updateProfile function correctly fetches the required data and returns it.
- [ ] Implement changes to the profile in the onUpdateProfile function
- [x] Test the function and handle errors
- [ ] Document the function
